<?php

use App\Http\Controllers\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DirectMessageController;
use App\Http\Controllers\DocumentApprovalController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\DocumentPreviewController;
use App\Http\Controllers\DocumentVersionController;
use App\Http\Controllers\FinanceController;
use App\Http\Controllers\FinanceDetailController;
use App\Http\Controllers\GovernanceController;
use App\Http\Controllers\InboundEmailController;
use App\Http\Controllers\MatterChronologyController;
use App\Http\Controllers\MatterController;
use App\Http\Controllers\MatterEventChecklistController;
use App\Http\Controllers\MatterOperationController;
use App\Http\Controllers\MatterReportController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SignatureArtifactController;
use App\Http\Controllers\SignatureReminderController;
use App\Http\Controllers\SignatureRequestController;
use App\Http\Controllers\SignatureSigningController;
use App\Http\Controllers\SignatureVerificationController;
use App\Http\Controllers\SystemReadinessController;
use App\Http\Controllers\TaskController;
use App\Http\Middleware\EnsureUserIsActive;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/dashboard')->name('home');

Route::get('verify/signature/{verificationCode}', [SignatureVerificationController::class, 'show'])->name('signature.verify');
Route::get('verify/signature/{verificationCode}/qr.svg', [SignatureVerificationController::class, 'qr'])->name('signature.qr');
Route::get('sign/{token}', [SignatureSigningController::class, 'show'])->middleware('throttle:signature-sign')->name('signature.sign.show');
Route::post('sign/{token}', [SignatureSigningController::class, 'store'])->middleware('throttle:signature-sign')->name('signature.sign.store');
Route::post('inbound/email', [InboundEmailController::class, 'store'])->middleware('throttle:30,1')->name('inbound.email.store');

Route::middleware(['auth', EnsureUserIsActive::class, 'verified'])->group(function () {
    Route::get('dashboard', DashboardController::class)->name('dashboard');
    Route::resource('matters', MatterController::class)->only(['index', 'create', 'store', 'show', 'update']);
    Route::post('matters/conflict-checks', [MatterController::class, 'storeConflictCheck'])->name('matters.conflict-checks.store');
    Route::post('matters/{matter}/parties', [MatterOperationController::class, 'storeParty'])->name('matters.parties.store');
    Route::post('matters/{matter}/deadlines', [MatterOperationController::class, 'storeDeadline'])->name('matters.deadlines.store');
    Route::post('matters/{matter}/events', [MatterOperationController::class, 'storeEvent'])->name('matters.events.store');
    Route::put('matters/{matter}/events/{event}/checklist', [MatterEventChecklistController::class, 'update'])->name('matters.events.checklist.update');
    Route::post('matters/{matter}/notes', [MatterOperationController::class, 'storeNote'])->name('matters.notes.store');
    Route::post('matters/{matter}/evidences', [MatterOperationController::class, 'storeEvidence'])->name('matters.evidences.store');
    Route::put('matters/{matter}/evidences/{evidence}', [MatterOperationController::class, 'updateEvidence'])->name('matters.evidences.update');
    Route::delete('matters/{matter}/evidences/{evidence}', [MatterOperationController::class, 'destroyEvidence'])->name('matters.evidences.destroy');
    Route::post('matters/{matter}/chronologies', [MatterChronologyController::class, 'store'])->name('matters.chronologies.store');
    Route::delete('matters/{matter}/chronologies/{chronology}', [MatterChronologyController::class, 'destroy'])->name('matters.chronologies.destroy');
    Route::get('matters/{matter}/chronologies/pdf', [MatterChronologyController::class, 'exportPdf'])->name('matters.chronologies.pdf');
    Route::get('matters/{matter}/status-report/pdf', [MatterReportController::class, 'statusReport'])->name('matters.status-report.pdf');
    Route::resource('clients', ClientController::class)->only(['index', 'create', 'store', 'show', 'edit', 'update']);
    Route::post('clients/{client}/compliance-documents', [ClientController::class, 'storeComplianceDocument'])->name('clients.compliance.store');
    Route::put('clients/{client}/compliance-documents/{complianceDocument}', [ClientController::class, 'updateComplianceDocument'])->name('clients.compliance.update');
    Route::delete('clients/{client}/compliance-documents/{complianceDocument}', [ClientController::class, 'destroyComplianceDocument'])->name('clients.compliance.destroy');
    Route::resource('contacts', ContactController::class)->only(['index', 'store', 'update']);
    Route::resource('tasks', TaskController::class)->only(['index', 'store', 'update']);
    Route::redirect('templates', '/documents')->name('templates.index');
    Route::post('comments', [CommentController::class, 'store'])->name('comments.store');
    Route::post('comments/{comment}/reaction', [CommentController::class, 'toggleReaction'])->name('comments.reaction');
    Route::post('comments/{comment}/pin', [CommentController::class, 'togglePin'])->name('comments.pin');
    Route::delete('comments/{comment}', [CommentController::class, 'destroy'])->name('comments.destroy');
    Route::get('calendar', CalendarController::class)->name('calendar.index');
    Route::get('calendar/export/ics', [CalendarController::class, 'exportIcs'])->name('calendar.export.ics');
    Route::get('finance', [FinanceController::class, 'index'])->name('finance.index');
    Route::get('finance/invoices/{invoice}', [FinanceDetailController::class, 'invoice'])->name('finance.invoices.show');
    Route::get('finance/payments/{payment}', [FinanceDetailController::class, 'payment'])->name('finance.payments.show');
    Route::get('finance/payments/{payment}/receipt', [FinanceDetailController::class, 'paymentReceipt'])->name('finance.payments.receipt');
    Route::post('finance/invoices', [FinanceController::class, 'storeInvoice'])->name('finance.invoices.store');
    Route::patch('finance/invoices/{invoice}/status', [FinanceController::class, 'transitionInvoice'])->name('finance.invoices.transition');
    Route::post('finance/quotations', [FinanceController::class, 'storeQuotation'])->name('finance.quotations.store');
    Route::post('finance/quotations/{quotation}/approve', [FinanceController::class, 'approveQuotation'])->name('finance.quotations.approve');
    Route::post('finance/expenses', [FinanceController::class, 'storeExpense'])->name('finance.expenses.store');
    Route::post('finance/payments', [FinanceController::class, 'storePayment'])->name('finance.payments.store');
    Route::post('finance/payments/{payment}/reverse', [FinanceController::class, 'reversePayment'])->name('finance.payments.reverse');
    Route::post('finance/payments/{payment}/refund', [FinanceController::class, 'refundPayment'])->name('finance.payments.refund');
    Route::get('finance/invoices/{invoice}/pdf', [FinanceController::class, 'downloadInvoice'])->name('finance.invoices.pdf');
    Route::get('finance/quotations/{quotation}/pdf', [FinanceController::class, 'downloadQuotation'])->name('finance.quotations.pdf');
    Route::get('governance', [GovernanceController::class, 'index'])->name('governance.index');
    Route::post('governance/correspondences', [GovernanceController::class, 'storeCorrespondence'])->name('governance.correspondences.store');
    Route::get('governance/correspondences/{correspondence}', [GovernanceController::class, 'showCorrespondence'])->name('governance.correspondences.show');
    Route::post('governance/correspondences/{correspondence}/attachments', [GovernanceController::class, 'storeCorrespondenceAttachment'])->name('governance.correspondences.attachments.store');
    Route::post('governance/conflict-checks', [GovernanceController::class, 'storeConflictCheck'])->name('governance.conflict-checks.store');
    Route::patch('governance/conflict-checks/{conflictCheck}', [GovernanceController::class, 'resolveConflictCheck'])->name('governance.conflict-checks.resolve');
    Route::post('governance/matters/{matter}/legal-hold', [GovernanceController::class, 'placeLegalHold'])->name('governance.matters.legal-hold.store');
    Route::delete('governance/matters/{matter}/legal-hold', [GovernanceController::class, 'releaseLegalHold'])->name('governance.matters.legal-hold.destroy');
    Route::post('governance/matters/{matter}/archive', [GovernanceController::class, 'archive'])->name('governance.matters.archive');
    Route::post('governance/matters/{matter}/exports', [GovernanceController::class, 'requestExport'])->name('governance.matters.exports.store');
    Route::get('governance/exports/{matterExport}/download', [GovernanceController::class, 'downloadExport'])->name('governance.exports.download');
    Route::resource('documents', DocumentController::class)->only(['index', 'store', 'show']);
    Route::post('documents/{document}/approvals', [DocumentApprovalController::class, 'store'])->name('documents.approvals.store');
    Route::patch('document-approvals/{approval}', [DocumentApprovalController::class, 'resolve'])->name('documents.approvals.resolve');
    Route::post('documents/{document}/signature-requests', [SignatureRequestController::class, 'store'])->name('documents.signature-requests.store');
    Route::post('signature-requests/{signatureRequest}/reminders', [SignatureReminderController::class, 'store'])->name('signature-requests.reminders.store');
    Route::get('signature-requests/{signatureRequest}/signed-record', [SignatureArtifactController::class, 'signedRecord'])->name('signature-requests.signed-record');
    Route::get('signature-requests/{signatureRequest}/signed-final', [SignatureArtifactController::class, 'signedFinal'])->name('signature-requests.signed-final');
    Route::get('signature-requests/{signatureRequest}/certificate', [SignatureArtifactController::class, 'certificate'])->name('signature-requests.certificate');
    Route::post('documents/{document}/versions', [DocumentVersionController::class, 'store'])->name('documents.versions.store');
    Route::get('documents/{document}/versions/{version}/download', [DocumentVersionController::class, 'download'])->name('documents.versions.download');
    Route::get('documents/{document}/versions/{version}/preview', [DocumentPreviewController::class, 'show'])->name('documents.versions.preview');
    Route::post('documents/{document}/versions/{version}/process', [DocumentPreviewController::class, 'process'])->name('documents.versions.process');
    Route::get('search', SearchController::class)->name('search');
    Route::get('chat', [DirectMessageController::class, 'index'])->name('chat.index');
    Route::get('api/chat/contacts', [DirectMessageController::class, 'contacts'])->name('chat.contacts');
    Route::get('api/chat/messages/{user}', [DirectMessageController::class, 'messages'])->name('chat.messages');
    Route::post('api/chat/messages/{message}/reaction', [DirectMessageController::class, 'toggleReaction'])->name('chat.reaction');
    Route::post('chat', [DirectMessageController::class, 'store'])->name('chat.store');
    Route::patch('notifications/{notification}/read', [NotificationController::class, 'read'])->name('notifications.read');
    Route::post('notifications/read-all', [NotificationController::class, 'readAll'])->name('notifications.read-all');
    Route::get('admin/audit', [AuditLogController::class, 'index'])->name('admin.audit.index');
    Route::get('admin/audit/export', [AuditLogController::class, 'export'])->name('admin.audit.export');
    Route::redirect('audit-logs', '/admin/audit');
    Route::redirect('audit', '/admin/audit');
    Route::get('admin/system-readiness', SystemReadinessController::class)->name('admin.system-readiness');
    Route::resource('admin/users', AdminUserController::class)->only(['index', 'store', 'update'])->names('admin.users');
    Route::put('admin/roles/{role}', [AdminRoleController::class, 'update'])->name('admin.roles.update');
});

require __DIR__.'/settings.php';
